2025-06-08 11:38:02,202 - app.config.logger - ERROR - Internal Server Error Occurred 2 validation errors:
  {'type': 'missing', 'loc': ('response', 'userId'), 'msg': 'Field required', 'input': <app.models.PostedRepoModel.PostedRepos object at 0x000001EA35E51190>}
  {'type': 'missing', 'loc': ('response', 'repoPostedBy', 'postedRepos', 0, 'userId'), 'msg': 'Field required', 'input': <app.models.PostedRepoModel.PostedRepos object at 0x000001EA35E51190>}

2025-06-08 11:47:26,303 - app.config.logger - INFO - All Repos Have been fetched
2025-06-08 11:47:27,143 - app.config.logger - ERROR - Internal Server Error Occurred 1 validation errors:
  {'type': 'missing', 'loc': ('response', 0, 'userId'), 'msg': 'Field required', 'input': <app.models.PostedRepoModel.PostedRepos object at 0x000002557A68B860>}

2025-06-08 11:50:13,836 - app.config.logger - INFO - All Repos Have been fetched
2025-06-08 11:57:22,311 - app.config.logger - ERROR - Not authenticated
2025-06-08 11:58:02,571 - app.config.logger - INFO - Repo With Id: 1 has been fetched successfully
2025-06-08 11:58:21,298 - app.config.logger - ERROR - Internal Server Error Occurred 'userId'
2025-06-08 11:59:46,384 - app.config.logger - ERROR - Internal Server Error Occurred 'user_id'
2025-06-08 12:01:07,734 - app.config.logger - ERROR - Error update repo posts with id 1: BaseModel.model_dump() missing 1 required positional argument: 'self'
2025-06-08 12:01:07,816 - app.config.logger - ERROR - Something went wrong while updating repo posts. BaseModel.model_dump() missing 1 required positional argument: 'self'
2025-06-08 12:05:55,703 - app.config.logger - INFO - Repo With Id: 1 has been updated successfully
2025-06-08 12:06:06,114 - app.config.logger - INFO - Repo With Id: 1 has been deleted successfully
2025-06-08 12:09:12,999 - app.config.logger - INFO - All Users Have been fetched
2025-06-08 12:11:17,180 - app.config.logger - INFO - All Users Have been fetched
2025-06-08 12:11:17,802 - app.config.logger - ERROR - Internal Server Error Occurred 1 validation errors:
  {'type': 'json_type', 'loc': ('response', 0, 'postedRepos', 0), 'msg': 'JSON input should be string, bytes or bytearray', 'input': <app.models.PostedRepoModel.PostedRepos object at 0x000001B397378800>}

2025-06-08 12:27:08,658 - app.config.logger - INFO - All Users Have been fetched
2025-06-08 16:45:19,006 - app.config.logger - INFO - All Users Have been fetched
2025-06-08 16:45:27,469 - app.config.logger - ERROR - Not Found
2025-06-08 16:45:31,561 - app.config.logger - ERROR - Not Found
2025-06-08 16:45:54,443 - app.config.logger - INFO - All Repos Have been fetched
2025-06-08 16:47:02,232 - app.config.logger - ERROR - Method Not Allowed
2025-06-08 16:47:08,576 - app.config.logger - INFO - All Repos Have been fetched
2025-06-08 16:59:32,363 - app.config.logger - ERROR - Not Found
2025-06-08 16:59:55,600 - app.config.logger - ERROR - Internal Server Error Occurred Unable to serialize unknown type: <class 'app.models.PostedRepoModel.PostedRepos'>
2025-06-08 17:08:22,788 - app.config.logger - INFO - All Users Have been fetched
2025-06-08 17:08:23,200 - app.config.logger - ERROR - Internal Server Error Occurred 1 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 0, 'postedRepos'), 'msg': 'Error extracting attribute: ProgrammingError: (psycopg2.errors.UndefinedTable) relation "postedRepos" does not exist\nLINE 2: FROM "postedRepos" \n             ^\n\n[SQL: SELECT "postedRepos".id AS "postedRepos_id", "postedRepos"."repoName" AS "postedRepos_repoName", "postedRepos"."repoDescription" AS "postedRepos_repoDescription", "postedRepos"."repoPrimaryLanguage" AS "postedRepos_repoPrimaryLanguage", "postedRepos"."repoId" AS "postedRepos_repoId", "postedRepos"."repoCustomLabels" AS "postedRepos_repoCustomLabels", "postedRepos"."repoHtmlUrl" AS "postedRepos_repoHtmlUrl", "postedRepos"."repoUrl" AS "postedRepos_repoUrl", "postedRepos"."repoTopics" AS "postedRepos_repoTopics", "postedRepos"."repoCloneUrl" AS "postedRepos_repoCloneUrl", "postedRepos"."repoGitUrl" AS "postedRepos_repoGitUrl", "postedRepos"."repoOpenIssuesCount" AS "postedRepos_repoOpenIssuesCount", "postedRepos"."repoForksCount" AS "postedRepos_repoForksCount", "postedRepos"."repoCustomTags" AS "postedRepos_repoCustomTags", "postedRepos"."repoOwner" AS "postedRepos_repoOwner", "postedRepos".user_id AS "postedRepos_user_id", "postedRepos"."upvotedUserIds" AS "postedRepos_upvotedUserIds", "postedRepos"."downvotedUserIds" AS "postedRepos_downvotedUserIds", "postedRepos"."upvotesCount" AS "postedRepos_upvotesCount", "postedRepos"."downvotesCount" AS "postedRepos_downvotesCount" \nFROM "postedRepos" \nWHERE %(param_1)s = "postedRepos".user_id]\n[parameters: {\'param_1\': 1}]\n(Background on this error at: https://sqlalche.me/e/20/f405)', 'input': <app.models.UserModel.User object at 0x0000014245A131A0>, 'ctx': {'error': 'ProgrammingError: (psycopg2.errors.UndefinedTable) relation "postedRepos" does not exist\nLINE 2: FROM "postedRepos" \n             ^\n\n[SQL: SELECT "postedRepos".id AS "postedRepos_id", "postedRepos"."repoName" AS "postedRepos_repoName", "postedRepos"."repoDescription" AS "postedRepos_repoDescription", "postedRepos"."repoPrimaryLanguage" AS "postedRepos_repoPrimaryLanguage", "postedRepos"."repoId" AS "postedRepos_repoId", "postedRepos"."repoCustomLabels" AS "postedRepos_repoCustomLabels", "postedRepos"."repoHtmlUrl" AS "postedRepos_repoHtmlUrl", "postedRepos"."repoUrl" AS "postedRepos_repoUrl", "postedRepos"."repoTopics" AS "postedRepos_repoTopics", "postedRepos"."repoCloneUrl" AS "postedRepos_repoCloneUrl", "postedRepos"."repoGitUrl" AS "postedRepos_repoGitUrl", "postedRepos"."repoOpenIssuesCount" AS "postedRepos_repoOpenIssuesCount", "postedRepos"."repoForksCount" AS "postedRepos_repoForksCount", "postedRepos"."repoCustomTags" AS "postedRepos_repoCustomTags", "postedRepos"."repoOwner" AS "postedRepos_repoOwner", "postedRepos".user_id AS "postedRepos_user_id", "postedRepos"."upvotedUserIds" AS "postedRepos_upvotedUserIds", "postedRepos"."downvotedUserIds" AS "postedRepos_downvotedUserIds", "postedRepos"."upvotesCount" AS "postedRepos_upvotesCount", "postedRepos"."downvotesCount" AS "postedRepos_downvotesCount" \nFROM "postedRepos" \nWHERE %(param_1)s = "postedRepos".user_id]\n[parameters: {\'param_1\': 1}]\n(Background on this error at: https://sqlalche.me/e/20/f405)'}}

2025-06-08 17:08:32,064 - app.config.logger - INFO - All Users Have been fetched
2025-06-08 17:08:32,473 - app.config.logger - ERROR - Internal Server Error Occurred 1 validation errors:
  {'type': 'get_attribute_error', 'loc': ('response', 0, 'postedRepos'), 'msg': 'Error extracting attribute: ProgrammingError: (psycopg2.errors.UndefinedTable) relation "postedRepos" does not exist\nLINE 2: FROM "postedRepos" \n             ^\n\n[SQL: SELECT "postedRepos".id AS "postedRepos_id", "postedRepos"."repoName" AS "postedRepos_repoName", "postedRepos"."repoDescription" AS "postedRepos_repoDescription", "postedRepos"."repoPrimaryLanguage" AS "postedRepos_repoPrimaryLanguage", "postedRepos"."repoId" AS "postedRepos_repoId", "postedRepos"."repoCustomLabels" AS "postedRepos_repoCustomLabels", "postedRepos"."repoHtmlUrl" AS "postedRepos_repoHtmlUrl", "postedRepos"."repoUrl" AS "postedRepos_repoUrl", "postedRepos"."repoTopics" AS "postedRepos_repoTopics", "postedRepos"."repoCloneUrl" AS "postedRepos_repoCloneUrl", "postedRepos"."repoGitUrl" AS "postedRepos_repoGitUrl", "postedRepos"."repoOpenIssuesCount" AS "postedRepos_repoOpenIssuesCount", "postedRepos"."repoForksCount" AS "postedRepos_repoForksCount", "postedRepos"."repoCustomTags" AS "postedRepos_repoCustomTags", "postedRepos"."repoOwner" AS "postedRepos_repoOwner", "postedRepos".user_id AS "postedRepos_user_id", "postedRepos"."upvotedUserIds" AS "postedRepos_upvotedUserIds", "postedRepos"."downvotedUserIds" AS "postedRepos_downvotedUserIds", "postedRepos"."upvotesCount" AS "postedRepos_upvotesCount", "postedRepos"."downvotesCount" AS "postedRepos_downvotesCount" \nFROM "postedRepos" \nWHERE %(param_1)s = "postedRepos".user_id]\n[parameters: {\'param_1\': 1}]\n(Background on this error at: https://sqlalche.me/e/20/f405)', 'input': <app.models.UserModel.User object at 0x00000142458A94F0>, 'ctx': {'error': 'ProgrammingError: (psycopg2.errors.UndefinedTable) relation "postedRepos" does not exist\nLINE 2: FROM "postedRepos" \n             ^\n\n[SQL: SELECT "postedRepos".id AS "postedRepos_id", "postedRepos"."repoName" AS "postedRepos_repoName", "postedRepos"."repoDescription" AS "postedRepos_repoDescription", "postedRepos"."repoPrimaryLanguage" AS "postedRepos_repoPrimaryLanguage", "postedRepos"."repoId" AS "postedRepos_repoId", "postedRepos"."repoCustomLabels" AS "postedRepos_repoCustomLabels", "postedRepos"."repoHtmlUrl" AS "postedRepos_repoHtmlUrl", "postedRepos"."repoUrl" AS "postedRepos_repoUrl", "postedRepos"."repoTopics" AS "postedRepos_repoTopics", "postedRepos"."repoCloneUrl" AS "postedRepos_repoCloneUrl", "postedRepos"."repoGitUrl" AS "postedRepos_repoGitUrl", "postedRepos"."repoOpenIssuesCount" AS "postedRepos_repoOpenIssuesCount", "postedRepos"."repoForksCount" AS "postedRepos_repoForksCount", "postedRepos"."repoCustomTags" AS "postedRepos_repoCustomTags", "postedRepos"."repoOwner" AS "postedRepos_repoOwner", "postedRepos".user_id AS "postedRepos_user_id", "postedRepos"."upvotedUserIds" AS "postedRepos_upvotedUserIds", "postedRepos"."downvotedUserIds" AS "postedRepos_downvotedUserIds", "postedRepos"."upvotesCount" AS "postedRepos_upvotesCount", "postedRepos"."downvotesCount" AS "postedRepos_downvotesCount" \nFROM "postedRepos" \nWHERE %(param_1)s = "postedRepos".user_id]\n[parameters: {\'param_1\': 1}]\n(Background on this error at: https://sqlalche.me/e/20/f405)'}}

2025-06-08 17:09:08,927 - app.config.logger - INFO - All Users Have been fetched
2025-06-08 17:10:15,643 - app.config.logger - ERROR - Validation Failed [{'type': 'missing', 'loc': ('body', 'languages'), 'msg': 'Field required', 'input': {'username': 'adi', 'email': 'adi@gmail.com', 'password': 'iloveadi'}}]
2025-06-08 17:10:34,598 - app.config.logger - INFO - User Created Successfully
2025-06-08 17:10:43,900 - app.config.logger - ERROR - Not Found
2025-06-08 17:10:50,313 - app.config.logger - INFO - User with ID 1 has been fetched successfully.
2025-06-08 17:18:07,998 - app.config.logger - ERROR - Validation Failed [{'type': 'missing', 'loc': ('body', 'username'), 'msg': 'Field required', 'input': {'repoUrl': 'https://github.com/mpiorowski/the-game', 'repoCustomLabels': ['test'], 'repoCustomTags': ['test'], 'repoTopics': ['web']}}, {'type': 'missing', 'loc': ('body', 'email'), 'msg': 'Field required', 'input': {'repoUrl': 'https://github.com/mpiorowski/the-game', 'repoCustomLabels': ['test'], 'repoCustomTags': ['test'], 'repoTopics': ['web']}}, {'type': 'missing', 'loc': ('body', 'password'), 'msg': 'Field required', 'input': {'repoUrl': 'https://github.com/mpiorowski/the-game', 'repoCustomLabels': ['test'], 'repoCustomTags': ['test'], 'repoTopics': ['web']}}, {'type': 'missing', 'loc': ('body', 'languages'), 'msg': 'Field required', 'input': {'repoUrl': 'https://github.com/mpiorowski/the-game', 'repoCustomLabels': ['test'], 'repoCustomTags': ['test'], 'repoTopics': ['web']}}]
2025-06-08 17:18:43,881 - app.config.logger - ERROR - Not authenticated
2025-06-08 17:19:10,060 - app.config.logger - INFO - All Users Have been fetched
2025-06-08 17:22:14,345 - app.config.logger - INFO - Authenticated User Found
2025-06-08 17:22:54,550 - app.config.logger - INFO - All Repos Have been fetched
2025-06-08 17:23:05,721 - app.config.logger - INFO - Repo With Id: 1 has been fetched successfully
2025-06-08 17:34:45,122 - app.config.logger - ERROR - Failed to post repo which has the repo url of https://github.com/mpiorowski/the-game and the error is (psycopg2.errors.UndefinedTable) relation "postedRepos" does not exist
LINE 2: FROM "postedRepos" 
             ^

[SQL: SELECT "postedRepos".id AS "postedRepos_id", "postedRepos"."repoName" AS "postedRepos_repoName", "postedRepos"."repoDescription" AS "postedRepos_repoDescription", "postedRepos"."repoPrimaryLanguage" AS "postedRepos_repoPrimaryLanguage", "postedRepos"."repoId" AS "postedRepos_repoId", "postedRepos"."repoCustomLabels" AS "postedRepos_repoCustomLabels", "postedRepos"."repoHtmlUrl" AS "postedRepos_repoHtmlUrl", "postedRepos"."repoUrl" AS "postedRepos_repoUrl", "postedRepos"."repoTopics" AS "postedRepos_repoTopics", "postedRepos"."repoCloneUrl" AS "postedRepos_repoCloneUrl", "postedRepos"."repoGitUrl" AS "postedRepos_repoGitUrl", "postedRepos"."repoOpenIssuesCount" AS "postedRepos_repoOpenIssuesCount", "postedRepos"."repoForksCount" AS "postedRepos_repoForksCount", "postedRepos"."repoCustomTags" AS "postedRepos_repoCustomTags", "postedRepos"."repoOwner" AS "postedRepos_repoOwner", "postedRepos".user_id AS "postedRepos_user_id", "postedRepos"."upvotedUserIds" AS "postedRepos_upvotedUserIds", "postedRepos"."downvotedUserIds" AS "postedRepos_downvotedUserIds", "postedRepos"."upvotesCount" AS "postedRepos_upvotesCount", "postedRepos"."downvotesCount" AS "postedRepos_downvotesCount" 
FROM "postedRepos" 
WHERE "postedRepos"."repoName" = %(repoName_1)s 
 LIMIT %(param_1)s]
[parameters: {'repoName_1': 'the-game', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-08 17:34:45,205 - app.config.logger - ERROR - Something went wrong while posting repo with https://github.com/mpiorowski/the-game and the error is (psycopg2.errors.UndefinedTable) relation "postedRepos" does not exist
LINE 2: FROM "postedRepos" 
             ^

[SQL: SELECT "postedRepos".id AS "postedRepos_id", "postedRepos"."repoName" AS "postedRepos_repoName", "postedRepos"."repoDescription" AS "postedRepos_repoDescription", "postedRepos"."repoPrimaryLanguage" AS "postedRepos_repoPrimaryLanguage", "postedRepos"."repoId" AS "postedRepos_repoId", "postedRepos"."repoCustomLabels" AS "postedRepos_repoCustomLabels", "postedRepos"."repoHtmlUrl" AS "postedRepos_repoHtmlUrl", "postedRepos"."repoUrl" AS "postedRepos_repoUrl", "postedRepos"."repoTopics" AS "postedRepos_repoTopics", "postedRepos"."repoCloneUrl" AS "postedRepos_repoCloneUrl", "postedRepos"."repoGitUrl" AS "postedRepos_repoGitUrl", "postedRepos"."repoOpenIssuesCount" AS "postedRepos_repoOpenIssuesCount", "postedRepos"."repoForksCount" AS "postedRepos_repoForksCount", "postedRepos"."repoCustomTags" AS "postedRepos_repoCustomTags", "postedRepos"."repoOwner" AS "postedRepos_repoOwner", "postedRepos".user_id AS "postedRepos_user_id", "postedRepos"."upvotedUserIds" AS "postedRepos_upvotedUserIds", "postedRepos"."downvotedUserIds" AS "postedRepos_downvotedUserIds", "postedRepos"."upvotesCount" AS "postedRepos_upvotesCount", "postedRepos"."downvotesCount" AS "postedRepos_downvotesCount" 
FROM "postedRepos" 
WHERE "postedRepos"."repoName" = %(repoName_1)s 
 LIMIT %(param_1)s]
[parameters: {'repoName_1': 'the-game', 'param_1': 1}]
(Background on this error at: https://sqlalche.me/e/20/f405)
2025-06-08 17:43:09,601 - app.config.logger - ERROR - User not found
2025-06-08 17:43:18,957 - app.config.logger - ERROR - Validation Failed [{'type': 'missing', 'loc': ('body', 'username'), 'msg': 'Field required', 'input': {'email': 'adi@gmail.com', 'password': 'iloveadi', 'name': 'adi', 'languages': ['go']}}]
2025-06-08 17:43:28,286 - app.config.logger - INFO - User Created Successfully
2025-06-08 17:43:58,659 - app.config.logger - INFO - Authenticated User Found
2025-06-08 17:44:33,998 - app.config.logger - INFO - Repo With Id: 1 has been fetched successfully
